# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import inventory_pb2 as inventory__pb2


class InventoryStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ready = channel.unary_unary(
                '/Inventory/Ready',
                request_serializer=inventory__pb2.NullMessage.SerializeToString,
                response_deserializer=inventory__pb2.NullMessage.FromString,
                )
        self.setProducts = channel.unary_unary(
                '/Inventory/setProducts',
                request_serializer=inventory__pb2.setProduct.SerializeToString,
                response_deserializer=inventory__pb2.TransactionResponse.FromString,
                )
        self.getProducts = channel.unary_unary(
                '/Inventory/getProducts',
                request_serializer=inventory__pb2.getProduct.SerializeToString,
                response_deserializer=inventory__pb2.TransactionResponse.FromString,
                )


class InventoryServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Ready(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def setProducts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getProducts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InventoryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ready': grpc.unary_unary_rpc_method_handler(
                    servicer.Ready,
                    request_deserializer=inventory__pb2.NullMessage.FromString,
                    response_serializer=inventory__pb2.NullMessage.SerializeToString,
            ),
            'setProducts': grpc.unary_unary_rpc_method_handler(
                    servicer.setProducts,
                    request_deserializer=inventory__pb2.setProduct.FromString,
                    response_serializer=inventory__pb2.TransactionResponse.SerializeToString,
            ),
            'getProducts': grpc.unary_unary_rpc_method_handler(
                    servicer.getProducts,
                    request_deserializer=inventory__pb2.getProduct.FromString,
                    response_serializer=inventory__pb2.TransactionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Inventory', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Inventory(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Ready(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Inventory/Ready',
            inventory__pb2.NullMessage.SerializeToString,
            inventory__pb2.NullMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def setProducts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Inventory/setProducts',
            inventory__pb2.setProduct.SerializeToString,
            inventory__pb2.TransactionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getProducts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Inventory/getProducts',
            inventory__pb2.getProduct.SerializeToString,
            inventory__pb2.TransactionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
