# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inventory.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finventory.proto\"\x18\n\ngetProduct\x12\n\n\x02id\x18\x01 \x01(\t\"*\n\nsetProduct\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\"*\n\x13TransactionResponse\x12\x13\n\x0bstatus_code\x18\x01 \x01(\x05\"\r\n\x0bNullMessage2\x94\x01\n\tInventory\x12#\n\x05Ready\x12\x0c.NullMessage\x1a\x0c.NullMessage\x12\x30\n\x0bsetProducts\x12\x0b.setProduct\x1a\x14.TransactionResponse\x12\x30\n\x0bgetProducts\x12\x0b.getProduct\x1a\x14.TransactionResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inventory_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GETPRODUCT._serialized_start=19
  _GETPRODUCT._serialized_end=43
  _SETPRODUCT._serialized_start=45
  _SETPRODUCT._serialized_end=87
  _TRANSACTIONRESPONSE._serialized_start=89
  _TRANSACTIONRESPONSE._serialized_end=131
  _NULLMESSAGE._serialized_start=133
  _NULLMESSAGE._serialized_end=146
  _INVENTORY._serialized_start=149
  _INVENTORY._serialized_end=297
# @@protoc_insertion_point(module_scope)
