# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eservices.proto\"\x18\n\ngetProduct\x12\n\n\x02id\x18\x01 \x01(\t\"*\n\nsetProduct\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\"*\n\naddToOrder\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\"\x1a\n\x0c\x63onfirmOrder\x12\n\n\x02id\x18\x01 \x01(\t\"*\n\x13TransactionResponse\x12\x13\n\x0bstatus_code\x18\x01 \x01(\x05\"\r\n\x0bNullMessage\"3\n\x07Package\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12\x17\n\x0fproductQuantity\x18\x02 \x01(\x05\".\n\x14ShipmentConfirmation\x12\x16\n\x0e\x61proximateDate\x18\x02 \x01(\t2\x94\x01\n\tInventory\x12#\n\x05Ready\x12\x0c.NullMessage\x1a\x0c.NullMessage\x12\x30\n\x0bsetProducts\x12\x0b.setProduct\x1a\x14.TransactionResponse\x12\x30\n\x0bgetProducts\x12\x0b.getProduct\x1a\x14.TransactionResponse2t\n\x0cShoppingCart\x12/\n\nAddProduct\x12\x0b.addToOrder\x1a\x14.TransactionResponse\x12\x33\n\x0c\x43onfirmOrder\x12\r.confirmOrder\x1a\x14.TransactionResponse2?\n\x08Shipment\x12\x33\n\x10ShipmentRegister\x12\x08.Package\x1a\x15.ShipmentConfirmationb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'services_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GETPRODUCT._serialized_start=18
  _GETPRODUCT._serialized_end=42
  _SETPRODUCT._serialized_start=44
  _SETPRODUCT._serialized_end=86
  _ADDTOORDER._serialized_start=88
  _ADDTOORDER._serialized_end=130
  _CONFIRMORDER._serialized_start=132
  _CONFIRMORDER._serialized_end=158
  _TRANSACTIONRESPONSE._serialized_start=160
  _TRANSACTIONRESPONSE._serialized_end=202
  _NULLMESSAGE._serialized_start=204
  _NULLMESSAGE._serialized_end=217
  _PACKAGE._serialized_start=219
  _PACKAGE._serialized_end=270
  _SHIPMENTCONFIRMATION._serialized_start=272
  _SHIPMENTCONFIRMATION._serialized_end=318
  _INVENTORY._serialized_start=321
  _INVENTORY._serialized_end=469
  _SHOPPINGCART._serialized_start=471
  _SHOPPINGCART._serialized_end=587
  _SHIPMENT._serialized_start=589
  _SHIPMENT._serialized_end=652
# @@protoc_insertion_point(module_scope)
