# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shoppingCart.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12shoppingCart.proto\"*\n\naddToOrder\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\"\x1a\n\x0c\x63onfirmOrder\x12\n\n\x02id\x18\x01 \x01(\t\"*\n\x13TransactionResponse\x12\x13\n\x0bstatus_code\x18\x01 \x01(\x05\x32t\n\x0cShoppingCart\x12/\n\nAddProduct\x12\x0b.addToOrder\x1a\x14.TransactionResponse\x12\x33\n\x0c\x43onfirmOrder\x12\r.confirmOrder\x1a\x14.TransactionResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'shoppingCart_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ADDTOORDER._serialized_start=22
  _ADDTOORDER._serialized_end=64
  _CONFIRMORDER._serialized_start=66
  _CONFIRMORDER._serialized_end=92
  _TRANSACTIONRESPONSE._serialized_start=94
  _TRANSACTIONRESPONSE._serialized_end=136
  _SHOPPINGCART._serialized_start=138
  _SHOPPINGCART._serialized_end=254
# @@protoc_insertion_point(module_scope)
