# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import shipment_pb2 as shipment__pb2


class ShipmentStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ShipmentRegister = channel.unary_unary(
                '/Shipment/ShipmentRegister',
                request_serializer=shipment__pb2.Package.SerializeToString,
                response_deserializer=shipment__pb2.ShipmentConfirmation.FromString,
                )


class ShipmentServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ShipmentRegister(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ShipmentServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ShipmentRegister': grpc.unary_unary_rpc_method_handler(
                    servicer.ShipmentRegister,
                    request_deserializer=shipment__pb2.Package.FromString,
                    response_serializer=shipment__pb2.ShipmentConfirmation.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Shipment', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Shipment(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ShipmentRegister(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Shipment/ShipmentRegister',
            shipment__pb2.Package.SerializeToString,
            shipment__pb2.ShipmentConfirmation.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
