# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shipment.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eshipment.proto\"3\n\x07Package\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12\x17\n\x0fproductQuantity\x18\x02 \x01(\x05\".\n\x14ShipmentConfirmation\x12\x16\n\x0e\x61proximateDate\x18\x02 \x01(\t2?\n\x08Shipment\x12\x33\n\x10ShipmentRegister\x12\x08.Package\x1a\x15.ShipmentConfirmationb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'shipment_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PACKAGE._serialized_start=18
  _PACKAGE._serialized_end=69
  _SHIPMENTCONFIRMATION._serialized_start=71
  _SHIPMENTCONFIRMATION._serialized_end=117
  _SHIPMENT._serialized_start=119
  _SHIPMENT._serialized_end=182
# @@protoc_insertion_point(module_scope)
